name: build

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  test:
    runs-on: ubuntu-latest
    environment: test
    steps:
    - uses: actions/checkout@v3

    - name: Setup Node
      uses: actions/setup-node@v3
      with:
        node-version: "^18.4.0"
        cache: "npm"

    - name: Install dependencies
      run: npm ci
    - run: npm run lint
    - run: npm run prettier -- --check
    - name: Sets variables to test
      env:
        ACCESS_TOKEN: ${{ secrets.VITE_ACCESS_TOKEN }}
        OAUTH_TOKEN: ${{ secrets.VITE_OAUTH_TOKEN }}
        SPACE_ID: ${{ vars.VITE_SPACE_ID }}
      run: npm run test
    - run: npm run build
