name: build
on:
  push:
    branches: [main]
  pull_request:
    branches: [main]
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Setup Node
        uses: actions/setup-node@v2
        with:
          node-version: "14"
          cache: "npm"
      - name: Install dependencies
        run: npm ci
      - run: npm run lint
      - run: npm run prettier -- --check
      - run: npm run test
      - run: npm run build
